# Generated by Django 2.0.7 on 2018-08-12 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='law',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='politik.LawProject'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
