# Generated by Django 2.0.7 on 2018-09-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politik', '0002_auto_20180812_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='foreign_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='politician',
            name='fu',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='politician',
            name='name',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='politician',
            name='party',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='politician',
            name='photoURL',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
